export type AdminLocale = "ar" | "fr" | "en";

export function getAdminLocale(locale: string): AdminLocale {
  return locale === "ar" || locale === "en" ? locale : "fr";
}

export const adminText = {
  ar: {
    brand: "ضياء",
    adminPanel: "لوحة الإدارة",
    dashboard: "الرئيسية",
    dashboardSubtitle: "نظرة شاملة على نشاط المنصة والطلبات",
    requests: "الطلبات",
    requestsDescription: "مراجعة طلبات المساعدة والتحقق منها قبل النشر",
    donations: "تبرعات الموقع",
    donationsSubtitle: "متابعة مساهمات دعم تكاليف تشغيل المنصة",
    users: "المستخدمون",
    usersSubtitle: "إدارة حسابات المستخدمين والصلاحيات",
    backToSite: "العودة للموقع",
    totalUsers: "المستخدمون",
    totalRequests: "الطلبات",
    pendingReviews: "قيد المراجعة",
    total: "المجموع",
    noRequests: "لا توجد طلبات حالياً",
    noDonations: "لا توجد تبرعات مسجلة حالياً.",
    noUsers: "لا يوجد مستخدمون حالياً.",
    reference: "المرجع",
    amount: "المبلغ",
    location: "الموقع",
    requester: "مقدم الطلب",
    anonymous: "مجهول",
    status: "الحالة",
    category: "الفئة",
    donor: "المتبرع",
    method: "الطريقة",
    date: "التاريخ",
    name: "الاسم",
    email: "البريد الإلكتروني",
    role: "الدور",
    joined: "تاريخ الانضمام",
    user: "مستخدم",
    admin: "مدير",
    notAvailable: "غير متوفر",
    secureAccess: "دخول آمن للوحة الإدارة",
    login: "تسجيل الدخول",
    loggingIn: "جار تسجيل الدخول...",
    password: "كلمة المرور",
    loginError: "تعذر تسجيل الدخول",
    unexpectedError: "حدث خطأ غير متوقع",
    backToList: "العودة للقائمة",
    notFound: "الطلب غير موجود",
    description: "الوصف",
    bankingInfo: "المعلومات البنكية",
    bank: "البنك",
    phone: "الهاتف",
    documents: "الوثائق",
    urgency: "الاستعجال",
    breakdown: "تفصيل المبلغ",
    submittedAt: "تاريخ الإرسال",
    reviewDecision: "قرار المراجعة",
    approve: "قبول",
    reject: "رفض",
    approved: "تم القبول",
    rejected: "تم الرفض",
    reviewNotesPlaceholder: "ملاحظات المراجعة...",
    logout: "تسجيل الخروج",
  },
  fr: {
    brand: "Diyae",
    adminPanel: "Administration",
    dashboard: "Tableau de bord",
    dashboardSubtitle: "Vue claire sur l'activité de la plateforme et les demandes",
    requests: "Demandes",
    requestsDescription: "Examiner et vérifier les demandes d'aide avant publication",
    donations: "Dons du site",
    donationsSubtitle: "Suivre les contributions aux frais de fonctionnement",
    users: "Utilisateurs",
    usersSubtitle: "Gérer les comptes et les rôles",
    backToSite: "Retour au site",
    totalUsers: "Utilisateurs",
    totalRequests: "Demandes",
    pendingReviews: "À examiner",
    total: "Total",
    noRequests: "Aucune demande pour le moment",
    noDonations: "Aucun don enregistré pour le moment.",
    noUsers: "Aucun utilisateur pour le moment.",
    reference: "Référence",
    amount: "Montant",
    location: "Localisation",
    requester: "Demandeur",
    anonymous: "Anonyme",
    status: "Statut",
    category: "Catégorie",
    donor: "Donateur",
    method: "Méthode",
    date: "Date",
    name: "Nom",
    email: "Email",
    role: "Rôle",
    joined: "Inscription",
    user: "Utilisateur",
    admin: "Admin",
    notAvailable: "Non renseigné",
    secureAccess: "Accès sécurisé à l'administration",
    login: "Connexion",
    loggingIn: "Connexion...",
    password: "Mot de passe",
    loginError: "Connexion impossible",
    unexpectedError: "Une erreur inattendue est survenue",
    backToList: "Retour à la liste",
    notFound: "Demande introuvable",
    description: "Description",
    bankingInfo: "Informations bancaires",
    bank: "Banque",
    phone: "Téléphone",
    documents: "Documents",
    urgency: "Urgence",
    breakdown: "Détail du montant",
    submittedAt: "Date de soumission",
    reviewDecision: "Décision d'examen",
    approve: "Approuver",
    reject: "Rejeter",
    approved: "Approuvé",
    rejected: "Rejeté",
    reviewNotesPlaceholder: "Notes d'examen...",
    logout: "Déconnexion",
  },
  en: {
    brand: "Diyae",
    adminPanel: "Administration",
    dashboard: "Dashboard",
    dashboardSubtitle: "A clear view of platform activity and requests",
    requests: "Requests",
    requestsDescription: "Review and verify assistance requests before publication",
    donations: "Site donations",
    donationsSubtitle: "Track contributions to operating costs",
    users: "Users",
    usersSubtitle: "Manage accounts and roles",
    backToSite: "Back to site",
    totalUsers: "Users",
    totalRequests: "Requests",
    pendingReviews: "Pending review",
    total: "Total",
    noRequests: "No requests at the moment",
    noDonations: "No donations recorded yet.",
    noUsers: "No users yet.",
    reference: "Reference",
    amount: "Amount",
    location: "Location",
    requester: "Requester",
    anonymous: "Anonymous",
    status: "Status",
    category: "Category",
    donor: "Donor",
    method: "Method",
    date: "Date",
    name: "Name",
    email: "Email",
    role: "Role",
    joined: "Joined",
    user: "User",
    admin: "Admin",
    notAvailable: "Not available",
    secureAccess: "Secure administration access",
    login: "Login",
    loggingIn: "Logging in...",
    password: "Password",
    loginError: "Login failed",
    unexpectedError: "An unexpected error occurred",
    backToList: "Back to list",
    notFound: "Request not found",
    description: "Description",
    bankingInfo: "Banking information",
    bank: "Bank",
    phone: "Phone",
    documents: "Documents",
    urgency: "Urgency",
    breakdown: "Amount breakdown",
    submittedAt: "Submitted on",
    reviewDecision: "Review decision",
    approve: "Approve",
    reject: "Reject",
    approved: "Approved",
    rejected: "Rejected",
    reviewNotesPlaceholder: "Review notes...",
    logout: "Logout",
  },
} as const;

export const statusLabels: Record<string, Record<AdminLocale, string>> = {
  DRAFT: { ar: "مسودة", fr: "Brouillon", en: "Draft" },
  SUBMITTED: { ar: "À examiner", fr: "À examiner", en: "Submitted" },
  REVIEW: { ar: "قيد المراجعة", fr: "En revue", en: "In review" },
  PUBLISHED: { ar: "منشور", fr: "Publié", en: "Published" },
  REJECTED: { ar: "مرفوض", fr: "Rejeté", en: "Rejected" },
  CLOSED: { ar: "مغلق", fr: "Clôturé", en: "Closed" },
  PENDING: { ar: "قيد الانتظار", fr: "En attente", en: "Pending" },
  SUCCEEDED: { ar: "تم بنجاح", fr: "Réussi", en: "Succeeded" },
  FAILED: { ar: "فشل", fr: "Échoué", en: "Failed" },
  REFUNDED: { ar: "مسترجع", fr: "Remboursé", en: "Refunded" },
};

export const urgencyLabels: Record<string, Record<AdminLocale, string>> = {
  NORMAL: { ar: "عادي", fr: "Normal", en: "Normal" },
  URGENT: { ar: "عاجل", fr: "Urgent", en: "Urgent" },
  CRITICAL: { ar: "حرج", fr: "Critique", en: "Critical" },
};

export function labelFor(
  labels: Record<string, Record<AdminLocale, string>>,
  key: string,
  locale: AdminLocale
) {
  return labels[key]?.[locale] ?? key;
}
