services:
  db:
    image: postgres:16
    container_name: zakkat-db
    restart: unless-stopped
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: app_zakkat
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - zakkat_data:/var/lib/postgresql/data

volumes:
  zakkat_data:
