import type { LucideIcon, LucideProps } from "lucide-react";
import {
  ArrowLeft,
  ArrowRight,
  Baby,
  BadgeCheck,
  Banknote,
  Bitcoin,
  Building2,
  CalendarDays,
  Camera,
  ChartNoAxesCombined,
  ChartPie,
  Check,
  ChevronDown,
  ChevronUp,
  CircleAlert,
  CircleCheck,
  CircleDollarSign,
  CircleX,
  ClipboardList,
  Clock3,
  Coins,
  Copy,
  CreditCard,
  Earth,
  Eye,
  ExternalLink,
  Feather,
  FileImage,
  FilePenLine,
  FileText,
  Gem,
  GraduationCap,
  HandHeart,
  Handshake,
  HeartPulse,
  Home,
  House,
  Inbox,
  Landmark,
  LayoutDashboard,
  Link,
  LockKeyhole,
  LogOut,
  MapPin,
  Menu,
  MoonStar,
  Package,
  ReceiptText,
  Scale,
  SearchCheck,
  Send,
  ShieldCheck,
  Sparkles,
  TrendingDown,
  Upload,
  UsersRound,
  WalletCards,
  Wheat,
  X,
} from "lucide-react";

const icons = {
  "arrow-left": ArrowLeft,
  "arrow-right": ArrowRight,
  baby: Baby,
  "badge-check": BadgeCheck,
  banknote: Banknote,
  bitcoin: Bitcoin,
  building: Building2,
  calendar: CalendarDays,
  camera: Camera,
  chart: ChartNoAxesCombined,
  "chart-pie": ChartPie,
  check: Check,
  "chevron-down": ChevronDown,
  "chevron-up": ChevronUp,
  alert: CircleAlert,
  success: CircleCheck,
  "circle-dollar": CircleDollarSign,
  error: CircleX,
  clipboard: ClipboardList,
  clock: Clock3,
  coins: Coins,
  copy: Copy,
  card: CreditCard,
  earth: Earth,
  eye: Eye,
  external: ExternalLink,
  feather: Feather,
  "file-image": FileImage,
  "file-edit": FilePenLine,
  file: FileText,
  gem: Gem,
  education: GraduationCap,
  "hand-heart": HandHeart,
  handshake: Handshake,
  medical: HeartPulse,
  home: Home,
  house: House,
  inbox: Inbox,
  landmark: Landmark,
  dashboard: LayoutDashboard,
  link: Link,
  lock: LockKeyhole,
  logout: LogOut,
  location: MapPin,
  menu: Menu,
  moon: MoonStar,
  package: Package,
  receipt: ReceiptText,
  scale: Scale,
  search: SearchCheck,
  send: Send,
  shield: ShieldCheck,
  sparkles: Sparkles,
  "trend-down": TrendingDown,
  upload: Upload,
  users: UsersRound,
  wallet: WalletCards,
  wheat: Wheat,
  close: X,
} satisfies Record<string, LucideIcon>;

export type AppIconName = keyof typeof icons;

type AppIconProps = Omit<LucideProps, "ref"> & {
  name: AppIconName;
};

export default function AppIcon({ name, strokeWidth = 1.8, ...props }: AppIconProps) {
  const Icon = icons[name];

  return <Icon aria-hidden="true" focusable="false" strokeWidth={strokeWidth} {...props} />;
}
